Repository hmcts/em-ped-api, pull requests merged in 2022-09, with the labels that each got.

#14 Added in keyvault
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:em, prd:em, add-or-update, rel:em-ped-api-pr-14

#19 Exposed the health check endpoint
  src/main/resources/application.yaml
Labels: ns:em, prd:em, rel:em-ped-api-pr-19

#20 Copy classes from icp
  build.gradle
  config/pmd/ruleset.xml
  src/functionalTest/java/uk/gov/hmcts/reform/em/ped/controllers/SampleFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/ped/config/SwaggerPublisherTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/em/ped/controllers/GetWelcomeTest.java
  src/main/java/uk/gov/hmcts/reform/em/ped/Application.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/OpenAPIConfiguration.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/StompConnectedEvent.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/StompDisconnectedEvent.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/StompSubscribedEvent.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/StompUnsubscribedEvent.java
  src/main/java/uk/gov/hmcts/reform/em/ped/config/WebSocketConfig.java
  src/main/java/uk/gov/hmcts/reform/em/ped/controllers/HearingSessionController.java
  src/main/java/uk/gov/hmcts/reform/em/ped/controllers/ParticipantsController.java
  src/main/java/uk/gov/hmcts/reform/em/ped/controllers/RootController.java
  src/main/java/uk/gov/hmcts/reform/em/ped/controllers/UpdateController.java
  src/main/java/uk/gov/hmcts/reform/em/ped/domain/HearingSession.java
  src/main/java/uk/gov/hmcts/reform/em/ped/domain/ParticipantStatus.java
  src/main/java/uk/gov/hmcts/reform/em/ped/domain/ScreenChange.java
  src/main/java/uk/gov/hmcts/reform/em/ped/domain/SubscriptionStatus.java
  src/main/java/uk/gov/hmcts/reform/em/ped/services/HearingSessionService.java
  src/main/java/uk/gov/hmcts/reform/em/ped/services/ParticipantsStatusService.java
  src/main/resources/application.yaml
  src/smokeTest/java/uk/gov/hmcts/reform/em/ped/controllers/SampleSmokeTest.java
  src/test/java/uk/gov/hmcts/reform/em/ped/DemoUnitTest.java
  src/test/java/uk/gov/hmcts/reform/em/ped/controllers/HearingSessionControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/ped/controllers/ParticipantsControllerTest.java
  src/test/java/uk/gov/hmcts/reform/em/ped/controllers/UpdateControllerTest.java
Labels: ns:em, prd:em, rel:em-ped-api-pr-20
